### ISSUE TITLE
Upgrade Sonar C# to 7

### ISSUE THREAD

**Issue by coolhome** [codacy/codacy-sonar-csharp#3]
Currently the engine is on 5.x which lacks support for C# 7.0. Support was introduced starting Sonar 7.5.

**Comment by IGFCoimbra** [comment]
Hi @coolhome 

I'm very sorry for the delay in getting back to you.

The Open Source community is an integral part of who we are and we are putting resources in place to make sure all past and future user contributions are reviewed in a timely manner moving forward. I have opened an internal ticket regarding this issue and it is already in our developers' queue. I will let you know as soon as we have any feedback on this.

Regards, 
Ivo

**Comment by coolhome** [comment]
@IGFCoimbra Thank you for keeping us update!

**Comment by Plazmaz** [comment]
FWIW I'd be interested to know the story behind #2. Is there something blocking this project from being updated?

**Comment by thiagodorneles** [comment]
Hi. I wanna know if this update will happen or not?

In the company that I work, we are using codacy, but we receive a lot of errors on code analysis because is not running is latest c# version

**Comment by coolhome** [comment]
@thiagodorneles [`sonar-dotnet`](https://github.com/SonarSource/sonar-dotnet) is made by the people who make `sonarcloud` and `sonarcube`. May be worth looking at if Codacy does not keep this module up to date :/

**Comment by gjsduarte** [comment]
We will close this after is deployed.
