### ISSUE TITLE
False positives on make Method static rule

### ISSUE THREAD

**Issue by rmcc13** [codacy/codacy-sonar-csharp#6]
I just added codacy to one of my .NET projects and it's really awesome. It provides a lot of useful information, however after running the analysis I get a lot of false positive issues on the make Method a static method rule. There are two scenarios I see issues for this rule that don't make sense. The first one is classes that implement an interface. Interface implementations must be instance methods, so this rule should not apply to those methods. Secondly, I have hundreds of these issues in my test projects. Test methods must be instance methods for the test framework to run them, so this rule should not apply to test methods.

I can deal with the false positives on interface implementations, but getting having to deal with the test issues becomes unwieldy and floods my codacy dashboard with noise, making it not very useful. Is there a way to disable a specific rule for a project for a filename pattern?

**Comment by ljmf00** [comment]
Hey @rmcc13 , can you check if it's still happening on this SonarC# version? I recently updated it to 7.16 and there's a lot of false positive fixes.

Thanks,
Luís

**Comment by ljmf00** [comment]
Hey @rmcc13 ,

I will consider this issue as resolved on the next tool updates. If you still have problems, feel free to reopen it.

Thanks,
Luis

**Comment by alanreyesv** [comment]
When is gonna be the next tool update?

**Comment by lolgab** [comment]
It already happened. Now we are pushing another update to Sonar `8.3` but the updated in the thread are already online.
