### ISSUE TITLE
Wrong error reported - Remove this unnecessary 'using'.

### ISSUE THREAD

**Issue by orantwolinkme** [codacy/codacy-sonar-csharp#67]
Sonar C# is asking to remove the using statement but it's required for System.Uri﻿

using System;

namespace Users
{
    public class UserRecord
    {
        public UserRecord(
            string authId,
            string email,
            string displayName,
            **Uri** photoUrl,
            CustomClaims customClaims,
            bool isDisabled)
        {
            AuthId = authId;
            Email = email;
            DisplayName = displayName;
            PhotoUrl = photoUrl;
            CustomClaims = customClaims;
            IsDisabled = isDisabled;
        }

        public string AuthId { get; }
        public string Email { get; }
        public string DisplayName { get; }
        public **_Uri_** PhotoUrl { get; }
        public CustomClaims CustomClaims { get; }
        public bool IsDisabled { get; }
    }
}

**Comment by lolgab** [comment]
You should report the issue on the original [sonar-dotnet](https://github.com/SonarSource/sonar-dotnet) repository
